# Generated by Django 3.2.4 on 2021-09-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
