# Generated by Django 3.2.7 on 2021-09-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_img',
            field=models.ImageField(default='default.png', upload_to='Profile_images'),
        ),
    ]
