# Generated by Django 3.2.4 on 2021-09-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='Phone',
            new_name='phone',
        ),
    ]
