# Generated by Django 3.2.4 on 2021-09-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management', '0003_rename_phone_restaurant_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
